language: java
jdk:
  - oraclejdk8
install: mvn install -Dmaven.compiler.target=8 -Dmaven.compiler.source=8 -DskipTests=true
script: cd common-dto-api && mvn test -Dmaven.compiler.target=8 -Dmaven.compiler.source=8 && cd ../com-turreta-soademo-configserver && mvn test -Dmaven.compiler.target=8 -Dmaven.compiler.source=8 && cd ../com-turreta-soademo-clientservice && mvn test -Dmaven.compiler.target=8 -Dmaven.compiler.source=8
